[package]
name = "taskcmd"
version = "0.1.4-dev"
authors = ["Dariusz Depta <depta@engos.de>"]
description = "Task commander"
documentation = "https://docs.rs/taskcmd"
repository = "https://github.com/EngosSoftware/taskcmd.git"
keywords = ["task", "commander"]
homepage = "https://engossoftware.github.io/taskcmd/"
categories = ["command-line-utilities"]
edition = "2024"
license = "MIT OR Apache-2.0"
include = [
    "docs/**",
    "src/**",
    "tests/**",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE*",
    "NOTICE",
    "/README.md"
]

[dependencies]
antex = "0.2.3"
idml = "0.6.0"
petgraph = "0.8.3"

[dev-dependencies]
cli-assert = "0.1.13-rc.0"
